services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Weatherlight foundation supervisor
  weatherlight:
    image: python:3.11-slim
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - ../:/app:rw
    env_file:
      - ../.env
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
    # Install repo in editable mode and run the Weatherlight console entrypoint
    command: bash -lc "pip install -q --no-cache-dir -e . && esper-weatherlight-service"

  # Optional: Nissa observability service (already has a console entrypoint)
  nissa:
    image: python:3.11-slim
    depends_on:
      - redis
    working_dir: /app
    volumes:
      - ../:/app:rw
    env_file:
      - ../.env
    command: bash -lc "pip install -q --no-cache-dir -e . && esper-nissa-service"
