name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    name: quality-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Ruff (lint)
        run: |
          ruff --version
          ruff check src tests

      - name: Pylint (lint)
        run: |
          pylint --rcfile .codacy/tools-configs/pylint.rc src/esper

      - name: Mypy (type-check)
        run: |
          mypy src/esper

      - name: Guard Shared Enums
        run: |
          python scripts/check_shared_types.py

  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: unit-tests
            pytest-args: >-
              -m "not integration and not performance" --cov=esper --cov-report=xml --cov-report=term
          - name: integration-tests
            pytest-args: -m integration
          - name: contract-tests
            pytest-args: tests/leyline/test_contracts.py
          - name: serialization-tests
            pytest-args: -m "not performance" tests/leyline/test_serialization.py

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run ${{ matrix.name }}
        env:
          REDIS_URL: redis://localhost:6379/0
        run: |
          pytest ${{ matrix.pytest-args }}

      - name: Upload coverage to Codacy
        if: ${{ github.event_name == 'push' && matrix.name == 'unit-tests' }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage.xml
        continue-on-error: true
